# manifest file to create pod
# kubectl run pod-1 --image=nginx    
apiVersion: v1
kind: Pod
metadata:
  name: crypto
  labels: 
    app: crypto
spec:
  containers:
    - name: container-1 
      image: abhipraydh96/bitcoin
---
# create service to access app
# kubectl expose pod crypto --port=80 --target-port=80 --type=NodePort
apiVersion: v1
kind: Service
metadata:
  name: svc-crypto
spec:
  selector:
    app: crypto
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: NodePort
  
